// From https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/discussions/1004

const mySubItemId = 'openapi/komga-api' // you can find this in the `sidebar.ts` items, its always the first in each category.

export function filterAutogeneratedSidebar (autogeneratedSidebar) {
    let filteredBar = (autogeneratedSidebar || []).map((item) => {
        if (item.type === 'category') {
            return {
                ...item,
                items: item.items.filter((subItem) => {
                    if (subItem.type === 'doc' && subItem.id.includes(mySubItemId)) {
                        return false
                    }

                    return true
                }),
            }
        }
        return item
    })

    // add the introduction at the top level
    filteredBar.unshift(
        {
            type: 'doc',
            id: 'openapi/komga-api',
        })

    return filteredBar
}