name: Test deployment

on:
  pull_request:
    branches: [master]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Mock OpenAPI
        run: npm -w website run mock-api-docs

      - name: Build website
        run: npm -w website run build